IMAGE_INSTALL_append = " hmi-apps"
IMAGE_INSTALL_append += " ffmpeg opkg"
IMAGE_INSTALL_append += " upgrade u-boot"
IMAGE_INSTALL_append += " opencv python3-opencv python3-numpy python3-matplotlib "
IMAGE_INSTALL_append += " live-camera-stream"
